import React from "react";
import { channel } from "@/lib/supabase";
import { Header } from "./components/header";
import { Card, CardContent } from "./components/common/card";
import "./globals.css";

export const metadata = {
  title: "The-Playmaker",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  channel
    .on("presence", { event: "sync" }, () => {
      const newState = channel.presenceState();
      console.log("sync", newState);
    })
    .on("presence", { event: "join" }, ({ key, newPresences }) => {
      console.log("join", key, newPresences);
    })
    .on("presence", { event: "leave" }, ({ key, leftPresences }) => {
      console.log("leave", key, leftPresences);
    })
    .subscribe(async (status) => {
      if (status === "SUBSCRIBED") {
        const presenceTrackStatus = await channel.track({
          user: "user-1",
          online_at: new Date().toISOString(),
        });
        console.log(presenceTrackStatus);
      }
    });
  return (
    <html>
      <body>
        <Header />
        <div className="bg-slate-50 flex justify-center">
          <span className="text-sm">
            You are not signed in. Please log in or register
          </span>
        </div>
        <div className="sm:px-4 xl:px-2 mx-2">
          <Card>
            <CardContent>
              <div className="flex justify-center">Announcement banner</div>
            </CardContent>
          </Card>
          <main className="flex h-screen flex-col flex-wrap w-full md:content-center">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
